### PR TITLE
add generality for type of client; add gmail example

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by bduggan** [comment]
Thanks for the PR!  Would you mind providing a bit more of a description for these changes?

**Comment by tbrowder** [comment]
Yes, Brian, as much as I can explain, my PR was needed for my situation for a local client on my PC so the default settings you had wouldn't work. My PR is probably not the smoothest but it works for my rough Gmail app. I don't know much about Oauth but I appreciate your getting the flow working. I would love for you to finish my local client work with an auto response so no visible browser is need and thus no human hand need click in a window.

I see that I left the PR in an awkward state due to the new example being incomplete. Also I can add a few comments and some tags in the `META6.json` file.

**Comment by 2colours** [comment]
I don't know how useful this PR is nowadays but can we have some feedback on it? In case it's an improvement over 6 years ago? @bduggan

**Comment by bduggan** [comment]
Sorry, @2colours -- I should've merged this a long time ago, thanks for the nudge.

**Pull request merged**
