### PR TITLE
Add `.save` and `.load` methods

### PR DESCRIPTION
**Pull request by nicqrocks**
These methods make it easier to save the objects to a file so that the user does not need to be asked for authentication every time.

Thought it could be useful. `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by bduggan-picwell** [comment]
Thanks for the PR!  I don't think I quite follow how the user is asked for auth each time, or what important information is being serialized in `save` that isn't in the google `client_id.json` file, would you mind giving me an example or elaborating a bit more?

**Comment by bduggan** [comment]
Thanks for the PR! I don't think I quite follow how the user is asked for auth each time, or what important information is being serialized in save that isn't in the google client_id.json file, would you mind giving me an example or elaborating a bit more?

**Comment by nicqrocks** [comment]
Yeah, I was thinking about that yesterday. Now that I look at it again, I realize that the token info is not actually stored in the object, so the `.save` and `.load` methods are not very useful. To get around that I started putting [this module](https://github.com/nicqrocks/perl6-oauth2-client-google-auto) together.
This PR can be closed as it really does not do much.

**Comment by bduggan** [comment]
Okay.  The -auto module looks nice!

**Pull request closed without merging**
